#            GAZE
#  Turnkey Open Media Centre
#              __        .-.
#          .-"` .`'.    /\\|
#  _(\-/)_" ,  .   ,\  /\\\/     =o O=
# {(=o^O=)} .   ./,  |/\\\/
# `-.(Y).-`  ,  |  , |\.-`
#      /~/,_/~~~\,__.-`   =O o=
#     ////~    // ~\\
#   ==`==`   ==`   ==`
#          monokal.io

version: '3'

networks:
  gaze:

services:
  # gaze:
  #   image: monokal/gaze:latest
  #   networks:
  #     - gaze
  #   ports:
  #     - "80:80"
  #   restart: always

  plex:
    image: plexinc/pms-docker:latest
    environment:
      - PLEX_CLAIM="${PLEX_CLAIM}"
      - ADVERTISE_IP="${PLEX_IP}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/radarr/movies:/data/movies
      - ./media/sonarr/series:/data/tv
      - ./media/plex/config/:/config
      - /tmp/transcode/:/transcode
    networks:
      - gaze
    ports:
      - "32400:32400"
    restart: always

  plexpy:
    image: linuxserver/plexpy:latest
    volumes:
      - ./media/plexpy:/config
      - ./media/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    depends_on:
      - plex
    networks:
      - gaze
    ports:
      - "8181:8181"
    restart: always

  transmission:
    image: linuxserver/transmission:latest
    networks:
      - gaze
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/transmission/config/:/config
      - ./media/transmission/downloads/:/downloads
    restart: always
    ports:
      - "9091:9091"

  sonarr:
    image: linuxserver/sonarr:latest
    networks:
      - gaze
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./media/sonarr/series:/tv
      - ./media/sonarr/config:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    depends_on:
      - transmission
    restart: always
    ports:
      - "8989:8989"

  radarr:
    image: linuxserver/radarr:latest
    networks:
      - gaze
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./media/radarr/movies:/movies
      - ./media/radarr/config:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    depends_on:
      - transmission
    restart: always
    ports:
      - "7878:7878"

  jackett:
    image: linuxserver/jackett:latest
    networks:
      - gaze
    volumes:
      - ./media/jackett/config/:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    restart: always
    ports:
      - "9117:9117"

  ombi:
    image: linuxserver/ombi
    networks:
      - gaze
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/ombi/config:/config
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    depends_on:
      - plex
      - sonarr
      - radarr
    restart: always
    ports:
      - "3579:3579"
