sudo: required

language: python

python:
  - "3.6"

services:
  - docker

install:
  - curl -L https://raw.githubusercontent.com/monokal/GAZE/master/gaze-control/gazectl-wrapper.sh > /tmp/gaze
  - chmod +x /tmp/gaze

script:
  - /tmp/gaze -d bootstrap
