#            GAZE
#  Turnkey Open Media Center
#              __        .-.
#          .-"` .`'.    /\\|
#  _(\-/)_" ,  .   ,\  /\\\/     =o O=
# {(=o^O=)} .   ./,  |/\\\/
# `-.(Y).-`  ,  |  , |\.-`
#      /~/,_/~~~\,__.-`   =O o=
#     ////~    // ~\\
#   ==`==`   ==`   ==`
#     gaze.monokal.io

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/96c2bf7be3231aee724b # Gitter.

    on_success: always
    on_failure: always
    on_start: always

sudo: required

branches:
  only:
    - master

os:
  - linux

language: generic

services:
  - docker

env:
  global:
    - GAZECTL_UPDATE=false # Don't pull the gazectl image if building locally.

install:
  - sudo pip install mkdocs
  - chmod +x gbuild.sh
  - chmod +x wrapper.sh

script:
  - ./gbuild.sh build
  - ./gbuild.sh test
