sudo: required

services:
  - docker

before_install:
- curl -L https://raw.githubusercontent.com/monokal/GAZE/master/gaze-control/gazectl-wrapper.sh > /tmp/gaze
- chmod +x /tmp/gaze
- /tmp/gaze bootstrap
