notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/96c2bf7be3231aee724b
    on_success: always
    on_failure: always
    on_start: always

sudo: required

language: python

python:
  - "3.6"

services:
  - docker

install:
  # Install build dependencies.
  - pip install mkdocs
  - pip install mkdocs-material

  # Install gazectl.
  - curl -L https://raw.githubusercontent.com/monokal/GAZE/master/gaze-control/gazectl-wrapper.sh > /tmp/gaze
  - chmod +x /tmp/gaze

  # Install gbuild.
  - curl -L https://raw.githubusercontent.com/monokal/GAZE/master/gbuild.sh > /tmp/gbuild
  - chmod +x /tmp/gbuild

script:
  - /tmp/gbuild build
  - /tmp/gbuild test
