#            GAZE
#  Turnkey Open Media Center
#              __        .-.
#          .-"` .`'.    /\\|
#  _(\-/)_" ,  .   ,\  /\\\/     =o O=
# {(=o^O=)} .   ./,  |/\\\/
# `-.(Y).-`  ,  |  , |\.-`
#      /~/,_/~~~\,__.-`   =O o=
#     ////~    // ~\\
#   ==`==`   ==`   ==`
#     gaze.monokal.io

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/96c2bf7be3231aee724b # Gitter.

    on_success: always
    on_failure: always
    on_start: always

sudo: required

os:
  - linux
  - osx

language: python

python:
  - "3.6"

services:
  - docker

env:
  global:
    - GAZECTL_VERSION='test'
    - GAZECTL_UPDATE=false # Disable Docker Image Pull as we're building locally.

install:
  - pip install mkdocs
  - pip install mkdocs-material

  - chmod +x gbuild.sh
  - chmod +x gaze-control/gazectl-wrapper.sh

script:
  - ./gbuild.sh build
  - ./gbuild.sh test
