#            GAZE
#     Media Centre Stack
#
# =o 0=        __        .-.
#          .-"` .`'.    /\\|
#  _(\-/)_" ,  .   ,\  /\\\/     =o O=
# {(=o^O=)} .   ./,  |/\\\/
# `-.(Y).-`  ,  |  , |\.-`
#      /~/,_/~~~\,__.-`   =O o=
#     ////~    // ~\\
#   ==`==`   ==`   ==`

version: '3'

services:
  plex:
    image: plexinc/pms-docker:latest
    networks:
      - web
    environment:
      - PLEX_CLAIM="${PLEX_TOKEN}"
      - ADVERTISE_IP="https://plex.${DOMAIN_NAME}/"
      - PLEX_UID=${USER_ID}
      - PLEX_GID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/radarr/movies:/data/movies
      - ./media/sonarr/series:/data/tvshows
      - ./media/plex/config/:/config
      - /tmp/transcode/:/transcode
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plex"
      - "traefik.frontend.rule=Host:plex.${DOMAIN_NAME}"
      - "traefik.port=32400"
      - "traefik.docker.network=web"
    depends_on:
      - transmission
      - sonarr
      - radarr
    ports:
      - "32400:32400"
    restart: always

  plexpy:
    image: linuxserver/plexpy:latest
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ./media/plexpy:/config
      - ./media/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plexpy"
      - "traefik.frontend.rule=Host:plexpy.${DOMAIN_NAME}"
      - "traefik.port=8181"
      - "traefik.docker.network=web"
    depends_on:
      - plex
    restart: always
    ports:
      - "8181:8181"

  transmission:
    image: linuxserver/transmission:latest
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/transmission/config/:/config
      - ./media/transmission/downloads/:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.backend=transmission"
      - "traefik.frontend.rule=Host:transmission.${DOMAIN_NAME}"
      - "traefik.port=9091"
      - "traefik.docker.network=web"
    restart: always
    ports:
      - "9091:9091"

  sonarr:
    image: linuxserver/sonarr:latest
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./media/sonarr/series:/tv
      - ./media/sonarr/config:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=sonarr"
      - "traefik.frontend.rule=Host:sonarr.${DOMAIN_NAME}"
      - "traefik.port=8989"
      - "traefik.docker.network=web"
    depends_on:
      - transmission
    restart: always
    ports:
      - "8989:8989"

  radarr:
    image: linuxserver/radarr:latest
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./media/radarr/movies:/movies
      - ./media/radarr/config:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=radarr"
      - "traefik.frontend.rule=Host:radarr.${DOMAIN_NAME}"
      - "traefik.port=7878"
      - "traefik.docker.network=web"
    depends_on:
      - transmission
    restart: always
    ports:
      - "7878:7878"

  # Proxy to a bunch of public trackers
  jackett:
    image: linuxserver/jackett:latest
    networks:
      - web
    volumes:
      - ./media/jackett/config/:/config
      - ./media/transmission/downloads/:/downloads
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=jackett"
      - "traefik.frontend.rule=Host:jackett.${DOMAIN_NAME}"
      - "traefik.port=9117"
      - "traefik.docker.network=web"
    restart: always
    ports:
      - "9117:9117"

  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: always
    ports:
      - "3579:3579"
    networks:
      - web
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./media/ombi/config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.backend=ombi"
      - "traefik.frontend.rule=Host:ombi.${DOMAIN_NAME}"
      - "traefik.port=3579"
      - "traefik.docker.network=web"

networks:
  web:
    external:
      name: reverseproxy_default
