site_name: GAZE
site_description: 'GAZE - Turnkey Open Media Center'
site_author: monokal.io
site_url: http://gaze.monokal.io
site_favicon: 'img/favicon.ico'

repo_url: 'https://github.com/monokal/gaze'

docs_dir: 'docs'

theme: readthedocs
# extra_css: [extra.css]
copyright: "Copyright &copy; monokal.io"

pages:
  - Quick Start: index.md
  - GAZE Control: control.md
  - GAZE Monitor: monitor.md
  - GAZE Proxy: proxy.md
  - Contribute: contribute.md
